Execute systemd stuff if ran by systemd
Signed-off-by: Amin Vakil <info@aminvakil.com>

diff --git a/cpack/debian/postinst.in b/cpack/debian/postinst.in
--- a/cpack/debian/postinst.in
+++ b/cpack/debian/postinst.in
@@ -1,7 +1,9 @@
 #!/bin/sh
 set -e
 @LDCONFIG_POSTINST_CMDS@
-if [ "$1" = "configure" ]; then
-    systemctl --system daemon-reload >/dev/null || true
-    systemctl try-restart @FLB_OUT_NAME@.service >/dev/null || true
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    if [ -d /run/systemd/system ]; then
+        systemctl --system daemon-reload >/dev/null || true
+        systemctl try-restart @FLB_OUT_NAME@.service >/dev/null || true
+    fi
 fi
