workflows: check for invalid branch on unstable builds
Signed-off-by: Patrick Stephens <pat@calyptia.com>

diff --git a/.github/workflows/cron-unstable-build.yaml b/.github/workflows/cron-unstable-build.yaml
--- a/.github/workflows/cron-unstable-build.yaml
+++ b/.github/workflows/cron-unstable-build.yaml
@@ -63,6 +63,10 @@ jobs:
         id: branch
         run: |
           echo "$cron_branch"
+          if [[ -z "$cron_branch" ]]; then
+            echo "Unable to determine branch to use"
+            exit 1
+          fi
           echo "::set-output name=branch::$cron_branch"
         shell: bash
 
